### ISSUE TITLE
Dockerize the application

### ISSUE THREAD

**Issue by khalilahmad1547** [khalilahmad1547/media-streaming-site#2]
**ToDo:**

- [ ] Dockerize the React App.
- [ ] Dockerize the Rails API backend.
- [ ] Create a docker-compose file for the whole app.
