### ISSUE TITLE
Setup Active Storage for dev and for production.

### ISSUE THREAD

**Issue by khalilahmad1547** [khalilahmad1547/media-streaming-site#3]
Active Storage is ruby's gem to manage files uploaded and storage, for development local storage is also good but a local S3 storage would be good.

**ToDo:**

- [ ] Basic Setup of Active Storage in Rails API.
- [ ] Set up MinIo for self-hosted S3 storage using a docker container.
- [ ] Update the .env.example file
- [ ] Update the docs for setting up the env
- [ ] Set up the docker secrets.
