### ISSUE TITLE
Create dababase setup for movies.

### ISSUE THREAD

**Issue by khalilahmad1547** [khalilahmad1547/media-streaming-site#4]
**ToDo:**

- [ ] Collect the meta info, e.g. required models to create
- [ ] Design the database ERD and add it to the docs.
- [ ] Collect the required attributes for each model in the design.
- [ ] Create models & add proper validation to each model in the Rails backend.
- [ ] Add associations from ERD to the Rails backend.
- [ ] Test models validation, required queries from rails console.
