### ISSUE TITLE
CRUD endpoints for movies.

### ISSUE THREAD

**Issue by khalilahmad1547** [khalilahmad1547/media-streaming-site#5]
**ToDo:**

- [ ] create policies for movie controllers.
- [ ] create a serializer for the movie model.
- [ ] create resource endpoint for the movie, (routes only).
- [ ] create index action.
- [ ] create show action.
- [ ] create create action.
- [ ] create update action.
- [ ] create delete action.
- [ ] apply the create policies for movie.
