### ISSUE TITLE
Downloade and save movie trallier from the YouTube.

### ISSUE THREAD

**Issue by khalilahmad1547** [khalilahmad1547/media-streaming-site#7]
Idea is to fetch data from TMDB ratings, descriptions other metadata. TMDB gives a link to the trailer on Youtube download it and save it to the database.

**ToDo:**

- [ ] Ruby code to downloade YouTube Vedios.
- [ ] Get the YouTube link of the trailer from TMDB.
- [ ] Create a job to download and update the movie with new data.
